create database project1;
create table if not exists person
(
    id        int generated by default as identity primary key,
    name      varchar(100) unique not null,
    birthyear int                 not null check ( birthyear > 1899 and birthyear < 2006)
);
insert into person (name, birthyear)
values ('Иванов Иван Иванович', 1954),
       ('Герасимов Федор Петрович', 2003),
       ('Аникин Акакий Акакьевич', 1975),
       ('Ананьев Ананий Ананьевич', 1993),
       ('Иванов Авокадий Петрович', 1926);


create table if not exists book
(
    id        int generated by default as identity primary key,
    name      varchar(100) not null,
    author    varchar(100) not null,
    year      int          not null check ( year < 2024 ),
    person_id int,
    constraint fk_person_id foreign key (person_id) references person (id) on delete set null
);

insert into book (name, author, year, person_id)
values ('Грокаем алгоритмы', 'Адитья Бхаргава', 2020, null),
       ('Война и мир', 'Лев Толстой', 1953, null),
       ('Божественная комедия', 'Данте Алигьери', 2016, null),
       ('Философия Java', 'Брюс Эккель', 2008, 4),
       ('Мечты роботов', 'Айзек Азимов', 1987, null),
       ('20 тысяч лье под водой', 'Жюль Верн', 1977, 3),
       ('Анна Каренина', 'Лев Толстой', 1990, 1),
       ('Малыш и Карлсон', 'Астрид Линдгрен', 2004, null),
       ('Остров сокровищ', 'Роберт Льюис Стивенсон', 2004, 1),
       ('Гарри Поттер и философский камень', 'Дж.К. Роулинг', 2009, 2);
